name: flutter_crypto_storage_example
description: Demonstrates how to use the flutter_crypto_storage plugin.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_crypto_storage:
    path: ../
  flutter_driver:
    sdk: flutter
  test: any
  lint: ^1.2.0

flutter:
  uses-material-design: true
