include: package:lint/analysis_options_package.yaml

linter:
  rules:
    prefer_single_quotes: true

analyzer:
  exclude:

  strong-mode:
    # Will become the default once non-nullable types land
    # https://github.com/dart-lang/sdk/issues/31410#issuecomment-510683629
    implicit-casts: false
    implicit-dynamic: false
  errors:
    # treat missing required parameters as an error (not a hint)
    missing_required_param: error
    # treat missing returns as an error (not a hint)
    missing_return: error
    # TODOs should become ticket links as soon as possible. Ideally before making a commit/PR.
    todo: warning
    dead_code: warning
