name: flutter_crypto_storage
description: |
  Flutter Crypto Storage was forked from flutter_secure_storage.
  Flutter Crypto Storage provides API to encrypt and store data securely on iOS and Android.
  Keychain is used in iOS, Androidx Crypto is used in Android.
version: 0.1.0
homepage: https://github.com/moneytree/flutter_secure_storage

flutter:
  plugin:
    androidPackage: jp.moneytree.security.crypto.storage
    pluginClass: FlutterCryptoStoragePlugin

dependencies:
  meta: "^1.1.2"
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  lint: ^1.2.0

environment:
    sdk: ">=2.0.0 <3.0.0"
    flutter: ">=1.10.0 <2.0.0"
